/// Flutter icons IconWeather
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconWeather
///      fonts:
///       - asset: fonts/IconWeather.ttf
///
///
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class IconWeather {
  IconWeather._();

  static const _kFontFam = 'IconWeather';
  static const _kFontPkg = null;

  static const IconData temperature =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData droplet =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_double_up =
      IconData(0xf102, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_double_down =
      IconData(0xf103, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperature_high =
      IconData(0xf769, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperature_low =
      IconData(0xf76b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
